### ISSUE TITLE
Is it possible to use without `.patch`?

### ISSUE THREAD

**Issue by robbyt** [TengHu/ActionWeaver#129]
Hello,
This library looks very interesting, but I would like to use it without patching the OpenAI client object. The documentation isn't clear if this will work.

Can I use the function decorator without patching the OpenAI object? Is there a way to use this library without patching?

Thanks!

**Comment by TengHu** [comment]
Hi @robbyt, currently patching the OpenAI client is the only way supported. Do you mind sharing what use case you have or concerns about patching the client object ?

**Comment by TengHu** [comment]
if you want to use the original openai client, you can use **action** decorator on the method, then invoke **get_function_details** method of that action, the method outputs all information needed by OpenAI

**Comment by TengHu** [comment]
Happy to chat more and help with your use case, feel free to join https://discord.gg/fnsnBB99C2 and ask any question.

**Comment by robbyt** [comment]
Thank you for the fast response, and the guidance to find the `get_function_details` method. 

On the topic of monkey-patching in Python... It's generally not idiomatic to do this, because it can cause unexpected issues with 3rd party code, and can be hard to maintain as the libraries are updated in the future.

It's a bit of a matter of preference, but the explicit approach tends to be better than implicit "magic" when writing Python.
(I'll check out the discord! thank you)

**Comment by TengHu** [comment]
Hi @robbyt, the latest release supports a composition approach for `wrapping` the OpenAI client, please checkout our readme and tutorials !
