### ISSUE TITLE
Azure OpenAI support

### ISSUE THREAD

**Issue by ranfysvalle02** [TengHu/ActionWeaver#41]
I'm struggling with getting it to work with Azure OpenAI. Is this coming soon?

**Comment by TengHu** [comment]
Thank you for your interest! Yes, I plan to work on that integration this weekend, will update here once I finish it.

**Comment by davidyao** [comment]
加上了也请告诉我哈~

**Comment by davidyao** [comment]
感谢~~~

**Comment by ranfysvalle02** [comment]
Thank you -- I was trying to fix it myself but ran into:

"InvalidRequestError: Unrecognized request argument supplied: functions"

AzureOpenAI is a requirement for some of my most interesting projects -- Looking forward to your update!! THANK YOU SO MUCH!

**Comment by ranfysvalle02** [comment]
It doesn't seem to like this part specifically -- 

```
if function_argument["functions"]:
                api_response = openai.ChatCompletion.create(
                    model=model,
                    deployment_id="",
                    temperature=temperature,
                    messages=messages,
                    stream=stream,
                    **function_argument,   <----------
                )
                ```

**Comment by ranfysvalle02** [comment]
Got some progress updating my model and the API version in the code

openai.api_version = "2023-07-01-preview"

```
openai.api_key = os.getenv("AZURE_OPENAI_KEY")
openai.api_version = "2023-07-01-preview"
openai.api_type = "azure"
openai.api_base = os.getenv("AZURE_OPENAI_ENDPOINT")
```

**Comment by ranfysvalle02** [comment]
New problem, but getting closer to success...

```
  File "/dev/RND/ActionWeaver/actionweaver/llms/azureopenai/chat.py", line 272, in create
    if "content" in first_element.choices[0]["delta"] and isinstance(
                    ~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

This is the area it seems to be complaining about...  
```
# logic to handle streaming API response
            if is_generator(api_response):
                first_element, iterator = get_first_element_and_iterator(api_response)
```

**Comment by ranfysvalle02** [comment]
Setting Stream=False gets things working with Azure OpenAI! 

```
response = self.llm.create(messages=self.messages, actions = [...], stream=False)

```

https://github.com/TengHu/ActionWeaver/pull/46/commits/20480d4d0a3d51f7e9d8cab9a1ffb5f147f9d540

**Comment by davidyao** [comment]
> Setting Stream=False gets things working with Azure OpenAI!
> 
> ```
> response = self.llm.create(messages=self.messages, actions = [...], stream=False)
> ```
> 
> [20480d4](https://github.com/TengHu/ActionWeaver/commit/20480d4d0a3d51f7e9d8cab9a1ffb5f147f9d540)

but streaming is so important for good user experience!

**Comment by TengHu** [comment]
Hey guys, the problem is Azure openai endpoint is returning data in a different format when streaming ([similar problem in haystack](https://github.com/deepset-ai/haystack/issues/5896)). I will start looking into azure streaming soon, also any PR is greatly appreciated !!

**Comment by ranfysvalle02** [comment]
https://github.com/ranfysvalle02/ActionWeaver/commit/b139e2b84fca3530828ae6c6abd1341578003164

I think this moves us closer to having Azure + ActionWeaver... 
<img width="833" alt="Screenshot 2023-11-07 at 2 46 15 PM" src="https://github.com/TengHu/ActionWeaver/assets/6230773/60339eea-8cfb-4d9a-bab3-d04fdfd2a241">

**Comment by TengHu** [comment]
Azure is now supported in 0.0.13 !! please take a look at this notebook https://github.com/TengHu/ActionWeaver/blob/main/docs/source/notebooks/azure.ipynb
